import type { Metadata } from "next";
import { Inter } from "next/font/google";
//Turbopack doesn't support PostCSS/Tailwind pipeline yet 
// so we have to work around it by building a css based in global.css and import it as so tubopack considers it normal css
// and not Tailwind CSS that it will ignore
// "dev": "npm run build:css && next dev --turbopack",
// "build:css": "tailwindcss -i src/app/styles/globals.css -o src/app/styles/tailwind.css --minify"
import "./styles/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
